data_path: ./data/cn15k/train.tsv
relation_id_path: ./data/cn15k/relation_id.tsv
out_data_path: ./data_for_psl_cn
Generate_Full_Target: False
Auto_remove_duplicate_triples: True
psl_model_name: demo
inference_method: LazyMPEInference

origin_data: False
predicates:
  - name: causes
    size: 2
    closed: False
  - name: partof
    size: 2
    closed: False

rules:
  - causes(P1, P2) & causes(P2, P3) -> causes(P1, P3) .
  - partof(P1, P2) & partof(P2, P3) -> partof(P1, P3) .


use_target: False
use_truth: False
inferred_result_path: test_full
out_softlogic_filename: softlogic.tsv