data_path: ./data/ppi5k/train.tsv
out_data_path: ./data_for_psl
Generate_Full_Target: False
Auto_remove_duplicate_triples: True
psl_model_name: demo
inference_method: LazyMPEInference
relation_id_path: ./data/ppi5k/relation_id.tsv
origin_data: False

predicates:
  - name: binding
    size: 2
    closed: False
  - name: catalysis
    size: 2
    closed: False
  - name: reaction
    size: 2
    closed: False
  - name: ptmod
    size: 2
    closed: False
  - name: activation
    size: 2
    closed: False
rules:
  - binding(P1, P2) & ptmod(P1, P2) -> activation(P1, P2) .
  - binding(P1, P2) & catalysis(P1, P2) -> reaction(P1, P2) .

use_target: False
use_truth: False
inferred_result_path: test
out_softlogic_filename: softlogic.tsv