accelerator: gpu
accumulate_grad_batches: 4
amp_backend: native
amp_level: O1
auto_lr_find: false
auto_scale_batch_size: false
auto_select_gpus: true
benchmark: true
check_val_every_n_epoch: 1
checkpoint_callback: null
checkpoint_dir: ''
config_path: ''
data_class: SAURDataModule
data_path: dataset/nl27k
dataset_name: nl27k
default_root_dir: null
deterministic: false
devices: [0]
early_stop_patience: 5
emb_dim: 768
hidden_dim: 10
output_dim: 128
input_size: 316
hidden_size: 128
enable_checkpointing: true
enable_model_summary: true
enable_progress_bar: true
eval_bs: 32
num_neg: 5
eval_task: simple_evaluation
fast_dev_run: false
gpu: 0
gpus: 1
gradient_clip_algorithm: norm
gradient_clip_val: 1.0
limit_predict_batches: 2.0e-05
limit_test_batches: 2.0e-05
limit_train_batches: 2.0e-05
limit_val_batches: 2.0e-05
litmodel_name: SAURLitModel
load_config: false
log_every_n_steps: 20
logger: true
loss_name: SAUR_Loss
lr: 0.001
max_epochs: 1
max_steps: 10
min_epochs: null
min_steps: null
model_name: SAUR
monitor: MSE
move_metrics_to_cpu: false
multiple_trainloader_mode: max_size_cycle
num_ent: 27000
num_workers: 0
num_rel: 16
num_sanity_val_steps: 1
optim_name: Adam
precision: 16
progress_bar_refresh_rate: 1
reload_dataloaders_every_epoch: false
reload_dataloaders_every_n_epochs: 0
replace_sampler_ddp: true
resume_from_checkpoint: null
save_config: true
seed: 42
shuffle: true
strategy: null
sync_batchnorm: false
test_only: false
test_sampler_class: RandomSampler
train_bs: 32
train_sampler_class: RandomSampler
use_wandb: false
val_check_interval: 1.0
weight_decay: 0.001
weights_save_path: null
weights_summary: top

regularization:
  entity: 0.01
  relation: 0.01
  attention: 0.01

confidence_filter: 0.7

root: NL27K
bert_embedding: bert_embedding
kg_pretrained_dir: ./bert_model

metric: link_prediction

ratio: 0.0010